trigger:
  branches:
    include:
      - main

stages:
  - stage: BuildAndDeploy
    displayName: 'Build and Deploy Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build and Test Job'
        pool:
          vmImage: 'ubuntu-latest'
        variables:
          pythonVersion: '3.9'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - script: |
              pytest tests/
            displayName: 'Run tests'

          - script: |
              zip -r app.zip .
            displayName: 'Package Application'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'FlaskDeployConnection'
              appName: 'riyas-cute-app'
              package: '$(System.DefaultWorkingDirectory)/app.zip'
